//! C ABI for the syodep core, consumed by the Qt shell.
//!
//! Conventions:
//!
//! - Every function is `extern "C"` and panic-safe (panics are caught and
//!   reported as errors / no-ops rather than unwinding into C++).
//! - The shell owns one `SyoApp` per window, created with [`syo_app_new`]
//!   and destroyed with [`syo_app_free`].
//! - Strings returned by the core are freed with [`syo_string_free`];
//!   bitmaps with [`syo_bitmap_free`]. Strings passed in are borrowed UTF-8.
//! - Key events arrive as the textual chord syntax from
//!   `syodep_config::keys` (e.g. `j`, `G`, `<C-d>`); the shell performs the
//!   purely mechanical Qt-event-to-string translation.
//!
//! The header `include/syodep_ffi.h` is generated by cbindgen at build time.
//!
//! Safety: this crate is the FFI boundary; all `unsafe` here is confined to
//! pointer/CString handling at the very edge. No MuPDF or Qt types cross
//! this boundary in either direction.

use std::ffi::{c_char, CStr, CString};
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::path::PathBuf;

use syodep_config::keys::parse_sequence;
use syodep_config::Config;
use syodep_core::{App, Effects, HighlightId, HighlightPdfState, TextAnnotationId};
use syodep_storage::Storage;

/// Opaque application handle.
pub struct SyoApp {
    app: App,
    /// Resolved starting directory for the Open dialog (absolute when known).
    open_dir: String,
    /// Human-readable provenance of `open_dir`, reported by `--check`.
    open_dir_source: String,
    /// Canvas background, resolved from `[view] background`.
    background_color: SyoColor,
    /// Highlight for focus mode, from `[view] focus_color`/`focus_opacity`.
    focus_color: SyoColor,
    /// Highlight for the visual selection, from `[view] visual_color`/`visual_opacity`.
    visual_color: SyoColor,
    /// Highlight colour, from `[view] highlight_color`/`highlight_opacity`.
    highlight_color: SyoColor,
    /// Pause before a half-typed sequence resolves, from `[input] timeout_ms`.
    key_timeout_ms: u32,
}

/// An RGBA colour resolved from the config, in 0-255 components.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SyoColor {
    pub r: u8,
    pub g: u8,
    pub b: u8,
    pub a: u8,
}

/// Resolve a configured `#rrggbb` plus an opacity into RGBA.
///
/// Never fails: an unparseable colour falls back to `fallback` and returns a
/// warning for the status bar, matching the rule that a bad config degrades
/// rather than aborting. Opacity is clamped to 0.0..=1.0 so a typo cannot make
/// the overlay invisible-by-arithmetic in a way that looks like a bug.
fn resolve_color(
    option: &str,
    value: &str,
    opacity: f32,
    fallback: &str,
) -> (SyoColor, Option<String>) {
    let (rgb, warning) = match syodep_config::parse_hex_color(value) {
        Some(rgb) => (rgb, None),
        None => (
            syodep_config::parse_hex_color(fallback).expect("built-in default colours are valid"),
            Some(format!(
                "invalid {option} {value:?} in [view]; using the default {fallback}"
            )),
        ),
    };
    let (r, g, b) = rgb;
    let a = (opacity.clamp(0.0, 1.0) * 255.0).round() as u8;
    (SyoColor { r, g, b, a }, warning)
}

/// Outcome of resolving the Open-dialog starting directory.
struct OpenDirResolution {
    /// Directory the dialog should open in (empty if even the CWD is unknown,
    /// in which case the shell lets Qt pick its own default).
    path: String,
    /// Short note on where the value came from, for `--check`.
    source: String,
    /// A startup warning to surface, set only when a configured directory was
    /// requested but could not be used.
    warning: Option<String>,
}

/// Resolve the Open-dialog starting directory.
///
/// Precedence: a configured `files.open_dir` that exists as a directory wins;
/// otherwise the launch (current working) directory is used. A configured path
/// that is missing or not a directory falls back to the launch directory and
/// produces a warning.
fn resolve_open_dir(configured: Option<&str>) -> OpenDirResolution {
    let cwd = std::env::current_dir()
        .ok()
        .map(|p| p.display().to_string())
        .unwrap_or_default();

    match configured {
        Some(raw) if !raw.trim().is_empty() => {
            if PathBuf::from(raw).is_dir() {
                OpenDirResolution {
                    path: raw.to_owned(),
                    source: format!("config: files.open_dir ({raw})"),
                    warning: None,
                }
            } else {
                OpenDirResolution {
                    path: cwd,
                    source: format!("config dir not found ({raw}) — using launch directory"),
                    warning: Some(format!(
                        "open_dir not found: {raw} — using launch directory"
                    )),
                }
            }
        }
        _ => OpenDirResolution {
            path: cwd,
            source: "launch directory".to_owned(),
            warning: None,
        },
    }
}

/// Effect bits returned by input functions.
pub const SYO_EFFECT_REDRAW: u32 = 1;
pub const SYO_EFFECT_QUIT: u32 = 2;
pub const SYO_EFFECT_OPEN_FILE_DIALOG: u32 = 4;
/// A partial key sequence is buffered. The shell should arm its pause timer
/// (see `syo_app_key_timeout_ms`) and call `syo_app_key_timeout` when it
/// fires; when this bit is clear it should cancel any armed timer.
pub const SYO_EFFECT_PENDING_INPUT: u32 = 8;
/// The document was reloaded from disk (a save rewrote it). Any page bitmaps the
/// shell is caching are stale even though the layout and zoom are unchanged, so
/// it must drop them.
pub const SYO_EFFECT_RELOAD: u32 = 16;
/// Quitting would lose highlights not yet embedded in the PDF. The shell
/// should ask (Save & Quit / Discard & Quit / Cancel) and call
/// `syo_app_quit_save` or `syo_app_quit_discard` with the answer, rather than
/// quitting outright.
pub const SYO_EFFECT_CONFIRM_QUIT: u32 = 32;
/// The annotation collection changed. Distinct from [`SYO_EFFECT_REDRAW`]: a
/// canvas refresh and a sidebar list refresh are different requests.
pub const SYO_EFFECT_ANNOTATIONS_CHANGED: u32 = 64;
/// Show or hide the highlights sidebar and move keyboard focus with it (see
/// `Effects::toggle_highlights_sidebar`). Sidebar visibility is shell state, so
/// this is a toggle request rather than a desired state.
pub const SYO_EFFECT_TOGGLE_HIGHLIGHTS_SIDEBAR: u32 = 128;
/// Show or hide the annotations sidebar page (see
/// `Effects::toggle_annotations_sidebar`).
pub const SYO_EFFECT_TOGGLE_ANNOTATIONS_SIDEBAR: u32 = 256;
/// A pending annotation anchor was captured; open the Annotations page in
/// creation mode (see `Effects::create_annotation_requested`). Never a hide.
pub const SYO_EFFECT_CREATE_ANNOTATION_REQUESTED: u32 = 512;

fn effects_to_bits(effects: Effects) -> u32 {
    let mut bits = 0;
    if effects.redraw {
        bits |= SYO_EFFECT_REDRAW;
    }
    if effects.quit {
        bits |= SYO_EFFECT_QUIT;
    }
    if effects.open_file_dialog {
        bits |= SYO_EFFECT_OPEN_FILE_DIALOG;
    }
    if effects.pending_input {
        bits |= SYO_EFFECT_PENDING_INPUT;
    }
    if effects.reload {
        bits |= SYO_EFFECT_RELOAD;
    }
    if effects.confirm_quit {
        bits |= SYO_EFFECT_CONFIRM_QUIT;
    }
    if effects.annotations_changed {
        bits |= SYO_EFFECT_ANNOTATIONS_CHANGED;
    }
    if effects.toggle_highlights_sidebar {
        bits |= SYO_EFFECT_TOGGLE_HIGHLIGHTS_SIDEBAR;
    }
    if effects.toggle_annotations_sidebar {
        bits |= SYO_EFFECT_TOGGLE_ANNOTATIONS_SIDEBAR;
    }
    if effects.create_annotation_requested {
        bits |= SYO_EFFECT_CREATE_ANNOTATION_REQUESTED;
    }
    bits
}

/// A page to draw, in canvas pixel coordinates.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SyoVisiblePage {
    pub page: usize,
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

/// One rectangle (canvas pixels) of an overlay.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SyoRect {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

/// A highlight overlay: zero or more rectangles (one per spanned line) in
/// canvas pixels. `valid` is 0 when the overlay is not active, in which case
/// `rects` is NULL and `rect_count` is 0. The `rects` buffer is owned by the
/// core and must be released with [`syo_overlay_free`].
///
/// Both the focus highlight and the visual selection use this shape, because a
/// focus highlight *is* a selection whose two ends coincide. There is no `page`
/// field: an overlay may span pages, and the rectangles are already in absolute
/// canvas coordinates.
#[repr(C)]
pub struct SyoOverlay {
    pub valid: u8,
    pub rects: *const SyoRect,
    pub rect_count: usize,
}

/// A tightly packed RGBA8 image (stride = width * 4).
#[repr(C)]
pub struct SyoBitmap {
    pub width: u32,
    pub height: u32,
    pub data: *mut u8,
    pub data_len: usize,
}

unsafe fn cstr_to_path(ptr: *const c_char) -> Option<PathBuf> {
    if ptr.is_null() {
        return None;
    }
    let s = unsafe { CStr::from_ptr(ptr) }.to_str().ok()?;
    Some(PathBuf::from(s))
}

fn to_c_string(s: String) -> *mut c_char {
    // Interior NULs cannot come from our own status/error strings, but be
    // defensive at the boundary.
    CString::new(s.replace('\0', " "))
        .expect("NUL bytes were just stripped")
        .into_raw()
}

/// Create the application core.
///
/// `config_path` and `db_path` may be NULL: a NULL config uses built-in
/// defaults, a NULL database path disables persistence. A config file that
/// fails to parse is reported as a startup warning (see
/// `syo_app_take_warnings`) and replaced by defaults; it never aborts.
///
/// # Safety
/// `config_path` and `db_path` must be NULL or valid NUL-terminated strings.
#[no_mangle]
pub unsafe extern "C" fn syo_app_new(
    config_path: *const c_char,
    db_path: *const c_char,
) -> *mut SyoApp {
    let config_path = unsafe { cstr_to_path(config_path) };
    let db_path = unsafe { cstr_to_path(db_path) };
    let result = catch_unwind(|| {
        let mut warnings = Vec::new();
        let config = match &config_path {
            Some(path) => match Config::load(path) {
                Ok(config) => config,
                Err(e) => {
                    warnings.push(format!("using default config: {e}"));
                    Config::default()
                }
            },
            None => Config::default(),
        };
        let storage = match &db_path {
            Some(path) => match Storage::open(path) {
                Ok(storage) => Some(storage),
                Err(e) => {
                    warnings.push(format!("persistence disabled: {e}"));
                    None
                }
            },
            None => None,
        };
        let open = resolve_open_dir(config.files.open_dir.as_deref());
        if let Some(warning) = open.warning {
            warnings.push(warning);
        }
        // The background is always opaque; only the overlays take an opacity.
        let (background_color, w) =
            resolve_color("background", &config.view.background, 1.0, "#1e1e1e");
        warnings.extend(w);
        let (focus_color, w) = resolve_color(
            "focus_color",
            &config.view.focus_color,
            config.view.focus_opacity,
            "#5b9bd5",
        );
        warnings.extend(w);
        let (visual_color, w) = resolve_color(
            "visual_color",
            &config.view.visual_color,
            config.view.visual_opacity,
            "#8a8a8a",
        );
        warnings.extend(w);
        let (highlight_color, w) = resolve_color(
            "highlight_color",
            &config.view.highlight_color,
            config.view.highlight_opacity,
            "#ffd400",
        );
        warnings.extend(w);
        let key_timeout_ms = config.input.timeout_ms;
        let mut app = App::new(config, storage);
        for warning in warnings {
            app.report_error(warning);
        }
        SyoApp {
            app,
            open_dir: open.path,
            open_dir_source: open.source,
            background_color,
            focus_color,
            visual_color,
            highlight_color,
            key_timeout_ms,
        }
    });
    match result {
        Ok(app) => Box::into_raw(Box::new(app)),
        Err(_) => std::ptr::null_mut(),
    }
}

/// Destroy the application core, persisting the reading position.
///
/// # Safety
/// `app` must be a pointer returned by `syo_app_new`, not freed before.
#[no_mangle]
pub unsafe extern "C" fn syo_app_free(app: *mut SyoApp) {
    if !app.is_null() {
        let boxed = unsafe { Box::from_raw(app) };
        let _ = catch_unwind(AssertUnwindSafe(move || drop(boxed)));
    }
}

/// Open a document. Returns true on success; on failure the previous
/// document (if any) stays open and the error is shown in the status text.
///
/// # Safety
/// `app` must be valid; `path` must be a valid NUL-terminated string.
#[no_mangle]
pub unsafe extern "C" fn syo_app_open_document(app: *mut SyoApp, path: *const c_char) -> bool {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return false;
    };
    let Some(path) = (unsafe { cstr_to_path(path) }) else {
        return false;
    };
    catch_unwind(AssertUnwindSafe(|| match app.app.open_document(&path) {
        Ok(()) => true,
        Err(e) => {
            app.app.report_error(e.to_string());
            false
        }
    }))
    .unwrap_or(false)
}

/// True when a document is open.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_has_document(app: *const SyoApp) -> bool {
    unsafe { app.as_ref() }
        .map(|a| a.app.has_document())
        .unwrap_or(false)
}

/// Inform the core of the canvas size in physical pixels.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_set_viewport(app: *mut SyoApp, width: f32, height: f32) {
    if let Some(app) = unsafe { app.as_mut() } {
        let _ = catch_unwind(AssertUnwindSafe(|| {
            app.app.set_viewport_size(width, height)
        }));
    }
}

/// Feed one key chord (textual syntax, e.g. "j", "G", "<C-d>", "<Esc>").
/// Returns SYO_EFFECT_* bits.
///
/// # Safety
/// `app` must be valid; `key` must be a valid NUL-terminated string.
#[no_mangle]
pub unsafe extern "C" fn syo_app_key_event(app: *mut SyoApp, key: *const c_char) -> u32 {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return 0;
    };
    if key.is_null() {
        return 0;
    }
    let Ok(key) = (unsafe { CStr::from_ptr(key) }).to_str() else {
        return 0;
    };
    catch_unwind(AssertUnwindSafe(|| {
        match parse_sequence(key).as_deref() {
            // The shell sends exactly one chord per key event.
            Ok([chord]) => effects_to_bits(app.app.handle_key(*chord)),
            _ => 0,
        }
    }))
    .unwrap_or(0)
}

/// Whether closing now would lose highlights not yet embedded in the PDF.
/// Read-only: used by the window-close path to decide whether to ask at all,
/// without the side effects a real quit-key press has (it never commits an
/// in-progress highlight).
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_has_unsaved_highlights(app: *const SyoApp) -> bool {
    unsafe { app.as_ref() }
        .map(|a| a.app.has_unsaved_highlights())
        .unwrap_or(false)
}

/// "Discard & Quit": quit without embedding unsaved highlights into the PDF.
/// Returns SYO_EFFECT_* bits (always includes SYO_EFFECT_QUIT).
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_quit_discard(app: *mut SyoApp) -> u32 {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return 0;
    };
    catch_unwind(AssertUnwindSafe(|| {
        effects_to_bits(app.app.quit_discarding_highlights())
    }))
    .unwrap_or(0)
}

/// "Save & Quit": embed unsaved highlights into the PDF, then quit. Returns
/// SYO_EFFECT_* bits — check SYO_EFFECT_QUIT: on failure the document stays
/// open and `syo_app_status_text` explains why.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_quit_save(app: *mut SyoApp) -> u32 {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return 0;
    };
    catch_unwind(AssertUnwindSafe(|| {
        effects_to_bits(app.app.save_and_quit())
    }))
    .unwrap_or(0)
}

/// How long (milliseconds) the shell should let a half-typed key sequence wait
/// before calling `syo_app_key_timeout`. From `[input] timeout_ms`; `0` means
/// the shell must not arm a timer at all.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_key_timeout_ms(app: *const SyoApp) -> u32 {
    match unsafe { app.as_ref() } {
        Some(app) => app.key_timeout_ms,
        None => 0,
    }
}

/// End a pending key sequence because the shell's pause timer fired. Returns
/// SYO_EFFECT_* bits; a no-op when nothing is pending, so the shell may call it
/// unconditionally.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_key_timeout(app: *mut SyoApp) -> u32 {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return 0;
    };
    catch_unwind(AssertUnwindSafe(|| {
        effects_to_bits(app.app.handle_timeout())
    }))
    .unwrap_or(0)
}

/// Scroll by a pixel delta (mouse wheel). Returns SYO_EFFECT_* bits.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_scroll_by(app: *mut SyoApp, dx: f32, dy: f32) -> u32 {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return 0;
    };
    catch_unwind(AssertUnwindSafe(|| {
        effects_to_bits(app.app.scroll_by_px(dx, dy))
    }))
    .unwrap_or(0)
}

/// Fill `out` with up to `capacity` visible pages; returns the number of
/// visible pages (which may exceed `capacity`; call again with more room).
///
/// # Safety
/// `app` must be valid; `out` must point to at least `capacity` elements.
#[no_mangle]
pub unsafe extern "C" fn syo_app_visible_pages(
    app: *const SyoApp,
    out: *mut SyoVisiblePage,
    capacity: usize,
) -> usize {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return 0;
    };
    let Ok(pages) = catch_unwind(AssertUnwindSafe(|| app.app.visible_pages())) else {
        return 0;
    };
    if !out.is_null() {
        for (i, page) in pages.iter().take(capacity).enumerate() {
            unsafe {
                *out.add(i) = SyoVisiblePage {
                    page: page.page,
                    x: page.rect.x,
                    y: page.rect.y,
                    width: page.rect.width,
                    height: page.rect.height,
                };
            }
        }
    }
    pages.len()
}

/// Collect screen rectangles into a freshly allocated [`SyoOverlay`].
fn overlay_from(rects: Option<Vec<syodep_core::layout::ScreenRect>>) -> SyoOverlay {
    match rects {
        Some(rects) if !rects.is_empty() => {
            let boxed: Box<[SyoRect]> = rects
                .into_iter()
                .map(|r| SyoRect {
                    x: r.x,
                    y: r.y,
                    width: r.width,
                    height: r.height,
                })
                .collect();
            let rect_count = boxed.len();
            let rects = Box::into_raw(boxed) as *const SyoRect;
            SyoOverlay {
                valid: 1,
                rects,
                rect_count,
            }
        }
        _ => invalid_overlay(),
    }
}

/// [`SyoOverlay`] owns a raw pointer and so is not `Copy`; build a fresh
/// "nothing to draw" value wherever one is needed rather than sharing one.
fn invalid_overlay() -> SyoOverlay {
    SyoOverlay {
        valid: 0,
        rects: std::ptr::null(),
        rect_count: 0,
    }
}

/// The focus highlight, one rectangle per spanned visible line. `valid` is 0
/// outside focus mode. One call covers every scope: what the highlight *is* --
/// a character, word, line, sentence or paragraph -- is the core's business,
/// not the shell's. The result must be released with [`syo_overlay_free`].
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_focus(app: *const SyoApp) -> SyoOverlay {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return invalid_overlay();
    };
    catch_unwind(AssertUnwindSafe(|| {
        overlay_from(app.app.focus_screen_rects())
    }))
    .unwrap_or_else(|_| invalid_overlay())
}

/// The visual-mode selection, one rectangle per spanned visible line. `valid`
/// is 0 outside visual mode. The result must be released with
/// [`syo_overlay_free`].
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_selection(app: *const SyoApp) -> SyoOverlay {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return invalid_overlay();
    };
    catch_unwind(AssertUnwindSafe(|| {
        overlay_from(app.app.visual_screen_rects())
    }))
    .unwrap_or_else(|_| invalid_overlay())
}

/// Pending highlights to paint on visible pages, plus the one being placed
/// while highlight mode is active. Embedded records are omitted (MuPDF draws
/// them). Distinct from [`syo_app_highlight_list`], which returns annotation
/// metadata for every stored highlight.
///
/// One call for both pending forms, and one colour, because the shell merges
/// an overlay's rectangles into a single fill — two overlays in the same colour
/// would double-blend wherever a pending highlight overlapped a stored one.
/// The result must be released with [`syo_overlay_free`].
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_highlights(app: *const SyoApp) -> SyoOverlay {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return invalid_overlay();
    };
    catch_unwind(AssertUnwindSafe(|| {
        overlay_from(app.app.highlight_screen_rects())
    }))
    .unwrap_or_else(|_| invalid_overlay())
}

/// Free the `rects` buffer of a [`SyoOverlay`]. A no-op for an invalid overlay,
/// so the shell can call it unconditionally.
///
/// # Safety
/// `overlay` must be a value returned by `syo_app_focus`, `syo_app_selection` or
/// `syo_app_highlights`, not freed before.
#[no_mangle]
pub unsafe extern "C" fn syo_overlay_free(overlay: SyoOverlay) {
    if overlay.rects.is_null() || overlay.rect_count == 0 {
        return;
    }
    unsafe {
        drop(Box::from_raw(std::ptr::slice_from_raw_parts_mut(
            overlay.rects as *mut SyoRect,
            overlay.rect_count,
        )));
    }
}

/// PDF lifecycle of a highlight annotation record (`0` Pending, `1` Embedded,
/// `2` External). Integer rather than a Rust enum so the C names match the
/// documented ABI without fighting Rust naming conventions.
pub type SyoHighlightState = i32;
pub const SYO_HIGHLIGHT_PENDING: SyoHighlightState = 0;
pub const SYO_HIGHLIGHT_EMBEDDED: SyoHighlightState = 1;
pub const SYO_HIGHLIGHT_EXTERNAL: SyoHighlightState = 2;

fn syo_highlight_state(state: HighlightPdfState) -> SyoHighlightState {
    match state {
        HighlightPdfState::Pending => SYO_HIGHLIGHT_PENDING,
        HighlightPdfState::Embedded => SYO_HIGHLIGHT_EMBEDDED,
        HighlightPdfState::External => SYO_HIGHLIGHT_EXTERNAL,
    }
}

/// One highlight for the annotations sidebar. `text` and `color` are owned heap
/// copies; free the whole list with [`syo_highlight_list_free`]. Pages are
/// zero-based (the shell displays them one-based).
#[repr(C)]
pub struct SyoHighlightItem {
    pub id: i64,
    pub first_page: usize,
    pub last_page: usize,
    pub text: *mut c_char,
    pub color: *mut c_char,
    pub state: SyoHighlightState,
}

/// Annotation snapshot for the open document. Owned by the caller; free with
/// [`syo_highlight_list_free`].
#[repr(C)]
pub struct SyoHighlightList {
    pub items: *mut SyoHighlightItem,
    pub count: usize,
    pub revision: u64,
}

fn empty_highlight_list(revision: u64) -> *mut SyoHighlightList {
    Box::into_raw(Box::new(SyoHighlightList {
        items: std::ptr::null_mut(),
        count: 0,
        revision,
    }))
}

/// Every highlight of the open document (Pending and Embedded), in document
/// order. Distinct from [`syo_app_highlights`], which returns screen-space
/// overlay geometry for Pending records only. Free with
/// [`syo_highlight_list_free`].
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_highlight_list(app: *const SyoApp) -> *mut SyoHighlightList {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return empty_highlight_list(0);
    };
    catch_unwind(AssertUnwindSafe(|| {
        let revision = app.app.annotation_revision();
        let summaries = app.app.highlight_summaries();
        if summaries.is_empty() {
            return empty_highlight_list(revision);
        }
        let mut items: Vec<SyoHighlightItem> = summaries
            .into_iter()
            .map(|s| SyoHighlightItem {
                id: s.id.0,
                first_page: s.first_page,
                last_page: s.last_page,
                text: to_c_string(s.text),
                color: to_c_string(s.color),
                state: syo_highlight_state(s.pdf_state),
            })
            .collect();
        let count = items.len();
        let items_ptr = items.as_mut_ptr();
        std::mem::forget(items);
        Box::into_raw(Box::new(SyoHighlightList {
            items: items_ptr,
            count,
            revision,
        }))
    }))
    .unwrap_or_else(|_| empty_highlight_list(0))
}

/// Free a list returned by [`syo_app_highlight_list`]. A no-op for NULL.
///
/// # Safety
/// `list` must be NULL or a pointer returned by [`syo_app_highlight_list`],
/// not freed before.
#[no_mangle]
pub unsafe extern "C" fn syo_highlight_list_free(list: *mut SyoHighlightList) {
    if list.is_null() {
        return;
    }
    let _ = catch_unwind(AssertUnwindSafe(|| unsafe {
        let list = Box::from_raw(list);
        if !list.items.is_null() && list.count > 0 {
            let items = Box::from_raw(std::ptr::slice_from_raw_parts_mut(list.items, list.count));
            for item in items.iter() {
                syo_string_free(item.text);
                syo_string_free(item.color);
            }
        }
    }));
}

/// Current annotation revision. See [`App::annotation_revision`].
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_annotation_revision(app: *const SyoApp) -> u64 {
    unsafe { app.as_ref() }
        .and_then(|a| catch_unwind(AssertUnwindSafe(|| a.app.annotation_revision())).ok())
        .unwrap_or(0)
}

/// Scroll so the highlight is visible, using only its stored geometry.
/// Returns [`SYO_EFFECT_*`](SYO_EFFECT_REDRAW) bits.
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_reveal_highlight(app: *mut SyoApp, highlight_id: i64) -> u32 {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return 0;
    };
    catch_unwind(AssertUnwindSafe(|| {
        effects_to_bits(app.app.reveal_highlight(HighlightId(highlight_id)))
    }))
    .unwrap_or(0)
}

/// Deterministic Markdown for one highlight. NULL when the id is unknown.
/// Free with [`syo_string_free`].
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_highlight_markdown(
    app: *const SyoApp,
    highlight_id: i64,
) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return std::ptr::null_mut();
    };
    catch_unwind(AssertUnwindSafe(|| {
        match app.app.highlight_markdown(HighlightId(highlight_id)) {
            Ok(md) => to_c_string(md),
            Err(_) => std::ptr::null_mut(),
        }
    }))
    .unwrap_or(std::ptr::null_mut())
}

/// Deterministic Markdown for every highlight, in canonical order. Free with
/// [`syo_string_free`]. An empty document yields an empty string, not NULL.
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_all_highlights_markdown(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    catch_unwind(AssertUnwindSafe(|| {
        to_c_string(app.app.all_highlights_markdown())
    }))
    .unwrap_or_else(|_| to_c_string(String::new()))
}

/// Delete a highlight of the open document.
///
/// A Pending highlight is removed from the database. An Embedded one is first
/// removed from the PDF by the `/NM` syodep wrote when embedding it, which
/// rewrites the file; on success `effects_out` therefore also carries
/// [`SYO_EFFECT_RELOAD`].
///
/// Returns true when the highlight is gone, writing effect bits to
/// `effects_out`. On failure (unknown id, no document, an embedded annotation
/// that cannot be identified in the PDF, a failed write, panic) returns false
/// and sets `effects_out` to zero when non-null; the reason is reported through
/// the core status path (`syo_app_status_text`).
///
/// # Safety
/// `app` must be NULL or valid. `effects_out` may be NULL.
#[no_mangle]
pub unsafe extern "C" fn syo_app_delete_highlight(
    app: *mut SyoApp,
    highlight_id: i64,
    effects_out: *mut u32,
) -> bool {
    let set_effects = |bits: u32| {
        if !effects_out.is_null() {
            unsafe {
                *effects_out = bits;
            }
        }
    };
    let Some(app) = (unsafe { app.as_mut() }) else {
        set_effects(0);
        return false;
    };
    match catch_unwind(AssertUnwindSafe(|| {
        app.app.delete_highlight(HighlightId(highlight_id))
    })) {
        Ok(Ok(effects)) => {
            set_effects(effects_to_bits(effects));
            true
        }
        Ok(Err(_)) | Err(_) => {
            set_effects(0);
            false
        }
    }
}

/// One text annotation for the sidebar. `text` and `body_markdown` are owned
/// heap copies of the complete source and complete Markdown body; free the
/// whole list with [`syo_text_annotation_list_free`].
#[repr(C)]
pub struct SyoTextAnnotationItem {
    pub id: i64,
    pub first_page: usize,
    pub last_page: usize,
    pub text: *mut c_char,
    pub body_markdown: *mut c_char,
}

#[repr(C)]
pub struct SyoTextAnnotationList {
    pub items: *mut SyoTextAnnotationItem,
    pub count: usize,
    pub revision: u64,
}

fn empty_text_annotation_list(revision: u64) -> *mut SyoTextAnnotationList {
    Box::into_raw(Box::new(SyoTextAnnotationList {
        items: std::ptr::null_mut(),
        count: 0,
        revision,
    }))
}

/// Every text annotation of the open document, in document order. Free with
/// [`syo_text_annotation_list_free`].
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_text_annotation_list(
    app: *const SyoApp,
) -> *mut SyoTextAnnotationList {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return empty_text_annotation_list(0);
    };
    catch_unwind(AssertUnwindSafe(|| {
        let revision = app.app.annotation_revision();
        let summaries = app.app.text_annotation_summaries();
        if summaries.is_empty() {
            return empty_text_annotation_list(revision);
        }
        let mut items: Vec<SyoTextAnnotationItem> = summaries
            .into_iter()
            .map(|s| SyoTextAnnotationItem {
                id: s.id.0,
                first_page: s.first_page,
                last_page: s.last_page,
                text: to_c_string(s.text),
                body_markdown: to_c_string(s.body_markdown),
            })
            .collect();
        let count = items.len();
        let items_ptr = items.as_mut_ptr();
        std::mem::forget(items);
        Box::into_raw(Box::new(SyoTextAnnotationList {
            items: items_ptr,
            count,
            revision,
        }))
    }))
    .unwrap_or_else(|_| empty_text_annotation_list(0))
}

/// Free a list returned by [`syo_app_text_annotation_list`].
///
/// # Safety
/// `list` must be NULL or a pointer from [`syo_app_text_annotation_list`].
#[no_mangle]
pub unsafe extern "C" fn syo_text_annotation_list_free(list: *mut SyoTextAnnotationList) {
    if list.is_null() {
        return;
    }
    let _ = catch_unwind(AssertUnwindSafe(|| unsafe {
        let list = Box::from_raw(list);
        if !list.items.is_null() && list.count > 0 {
            let items = Box::from_raw(std::ptr::slice_from_raw_parts_mut(list.items, list.count));
            for item in items.iter() {
                syo_string_free(item.text);
                syo_string_free(item.body_markdown);
            }
        }
    }));
}

/// Captured source text of the pending annotation, or NULL when none.
/// Free with [`syo_string_free`].
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_pending_annotation_text(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return std::ptr::null_mut();
    };
    catch_unwind(AssertUnwindSafe(|| {
        match app.app.pending_annotation_anchor() {
            Some(anchor) => to_c_string(anchor.text.clone()),
            None => std::ptr::null_mut(),
        }
    }))
    .unwrap_or(std::ptr::null_mut())
}

/// Drop a pending annotation create without writing a row.
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_cancel_pending_annotation(app: *mut SyoApp) {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return;
    };
    let _ = catch_unwind(AssertUnwindSafe(|| app.app.cancel_pending_annotation()));
}

/// Whether SQLite persistence is available for annotations.
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_has_persistence(app: *const SyoApp) -> bool {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return false;
    };
    catch_unwind(AssertUnwindSafe(|| app.app.has_persistence())).unwrap_or(false)
}

/// Persist a new text annotation from the pending anchor. Returns true and
/// writes the new id plus effect bits on success. Trimmed-empty bodies fail.
///
/// # Safety
/// `app` must be NULL or valid. `body_markdown` must be a valid C string.
/// `out_id` and `effects_out` may be NULL.
#[no_mangle]
pub unsafe extern "C" fn syo_app_create_text_annotation(
    app: *mut SyoApp,
    body_markdown: *const c_char,
    out_id: *mut i64,
    effects_out: *mut u32,
) -> bool {
    let set_effects = |bits: u32| {
        if !effects_out.is_null() {
            unsafe {
                *effects_out = bits;
            }
        }
    };
    let set_id = |id: i64| {
        if !out_id.is_null() {
            unsafe {
                *out_id = id;
            }
        }
    };
    let Some(app) = (unsafe { app.as_mut() }) else {
        set_id(0);
        set_effects(0);
        return false;
    };
    if body_markdown.is_null() {
        set_id(0);
        set_effects(0);
        return false;
    }
    let Ok(body) = (unsafe { CStr::from_ptr(body_markdown) }).to_str() else {
        set_id(0);
        set_effects(0);
        return false;
    };
    match catch_unwind(AssertUnwindSafe(|| {
        app.app.create_text_annotation(body.to_owned())
    })) {
        Ok(Ok((id, effects))) => {
            set_id(id.0);
            set_effects(effects_to_bits(effects));
            true
        }
        Ok(Err(_)) | Err(_) => {
            set_id(0);
            set_effects(0);
            false
        }
    }
}

/// Replace the Markdown body of an existing text annotation.
///
/// # Safety
/// `app` must be NULL or valid. `body_markdown` must be a valid C string.
/// `effects_out` may be NULL.
#[no_mangle]
pub unsafe extern "C" fn syo_app_set_text_annotation_body(
    app: *mut SyoApp,
    annotation_id: i64,
    body_markdown: *const c_char,
    effects_out: *mut u32,
) -> bool {
    let set_effects = |bits: u32| {
        if !effects_out.is_null() {
            unsafe {
                *effects_out = bits;
            }
        }
    };
    let Some(app) = (unsafe { app.as_mut() }) else {
        set_effects(0);
        return false;
    };
    if body_markdown.is_null() {
        set_effects(0);
        return false;
    }
    let Ok(body) = (unsafe { CStr::from_ptr(body_markdown) }).to_str() else {
        set_effects(0);
        return false;
    };
    match catch_unwind(AssertUnwindSafe(|| {
        app.app
            .set_text_annotation_body(TextAnnotationId(annotation_id), body.to_owned())
    })) {
        Ok(Ok(effects)) => {
            set_effects(effects_to_bits(effects));
            true
        }
        Ok(Err(_)) | Err(_) => {
            set_effects(0);
            false
        }
    }
}

/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_reveal_text_annotation(
    app: *mut SyoApp,
    annotation_id: i64,
) -> u32 {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return 0;
    };
    catch_unwind(AssertUnwindSafe(|| {
        effects_to_bits(
            app.app
                .reveal_text_annotation(TextAnnotationId(annotation_id)),
        )
    }))
    .unwrap_or(0)
}

/// # Safety
/// `app` must be NULL or valid. `effects_out` may be NULL.
#[no_mangle]
pub unsafe extern "C" fn syo_app_delete_text_annotation(
    app: *mut SyoApp,
    annotation_id: i64,
    effects_out: *mut u32,
) -> bool {
    let set_effects = |bits: u32| {
        if !effects_out.is_null() {
            unsafe {
                *effects_out = bits;
            }
        }
    };
    let Some(app) = (unsafe { app.as_mut() }) else {
        set_effects(0);
        return false;
    };
    match catch_unwind(AssertUnwindSafe(|| {
        app.app
            .delete_text_annotation(TextAnnotationId(annotation_id))
    })) {
        Ok(Ok(effects)) => {
            set_effects(effects_to_bits(effects));
            true
        }
        Ok(Err(_)) | Err(_) => {
            set_effects(0);
            false
        }
    }
}

/// Deterministic Markdown for one text annotation. NULL when unknown.
/// Free with [`syo_string_free`].
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_text_annotation_markdown(
    app: *const SyoApp,
    annotation_id: i64,
) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return std::ptr::null_mut();
    };
    catch_unwind(AssertUnwindSafe(|| {
        match app
            .app
            .text_annotation_markdown(TextAnnotationId(annotation_id))
        {
            Ok(md) => to_c_string(md),
            Err(_) => std::ptr::null_mut(),
        }
    }))
    .unwrap_or(std::ptr::null_mut())
}

/// Deterministic Markdown for every text annotation. Free with
/// [`syo_string_free`].
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_all_text_annotations_markdown(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    catch_unwind(AssertUnwindSafe(|| {
        to_c_string(app.app.all_text_annotations_markdown())
    }))
    .unwrap_or_else(|_| to_c_string(String::new()))
}

/// Render a page at the current zoom. Returns NULL on failure. The result
/// must be freed with `syo_bitmap_free`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_render_page(app: *mut SyoApp, page: usize) -> *mut SyoBitmap {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return std::ptr::null_mut();
    };
    if !app.app.has_document() {
        return std::ptr::null_mut();
    }
    let result = catch_unwind(AssertUnwindSafe(|| match app.app.render_page(page) {
        Ok(bitmap) => {
            let mut data = bitmap.data.clone().into_boxed_slice();
            let out = SyoBitmap {
                width: bitmap.width,
                height: bitmap.height,
                data: data.as_mut_ptr(),
                data_len: data.len(),
            };
            std::mem::forget(data);
            Box::into_raw(Box::new(out))
        }
        Err(e) => {
            app.app.report_error(e.to_string());
            std::ptr::null_mut()
        }
    }));
    result.unwrap_or(std::ptr::null_mut())
}

/// Free a bitmap returned by `syo_app_render_page`.
///
/// # Safety
/// `bitmap` must be NULL or a pointer returned by `syo_app_render_page`,
/// not freed before.
#[no_mangle]
pub unsafe extern "C" fn syo_bitmap_free(bitmap: *mut SyoBitmap) {
    if bitmap.is_null() {
        return;
    }
    unsafe {
        let bitmap = Box::from_raw(bitmap);
        if !bitmap.data.is_null() {
            drop(Box::from_raw(std::ptr::slice_from_raw_parts_mut(
                bitmap.data,
                bitmap.data_len,
            )));
        }
    }
}

/// Status line text. Free with `syo_string_free`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_status_text(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    let text = catch_unwind(AssertUnwindSafe(|| app.app.status_text())).unwrap_or_default();
    to_c_string(text)
}

/// Startup warnings (bad config entries etc.), newline-separated; empty
/// string when there are none. Free with `syo_string_free`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_startup_warnings(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    let text = catch_unwind(AssertUnwindSafe(|| app.app.startup_warnings().join("\n")))
        .unwrap_or_default();
    to_c_string(text)
}

/// Canvas background colour from `[view] background` (always opaque).
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_background_color(app: *const SyoApp) -> SyoColor {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return SyoColor {
            r: 0x1e,
            g: 0x1e,
            b: 0x1e,
            a: 255,
        };
    };
    app.background_color
}

/// Highlight colour for focus mode, from `[view] focus_color` and
/// `focus_opacity`. One colour covers every scope: the highlight signals that
/// focus is active, not which granularity is in use.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_focus_color(app: *const SyoApp) -> SyoColor {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return SyoColor {
            r: 0xad,
            g: 0xd8,
            b: 0xe6,
            a: 102,
        };
    };
    app.focus_color
}

/// Highlight colour for the visual-mode selection, from `[view] visual_color`
/// and `visual_opacity`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_visual_color(app: *const SyoApp) -> SyoColor {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return SyoColor {
            r: 0xd3,
            g: 0xd3,
            b: 0xd3,
            a: 102,
        };
    };
    app.visual_color
}

/// Colour of a highlight, from `[view] highlight_color` and
/// `highlight_opacity`. Used for both the pending and the stored ones — the
/// signal is "this text is highlighted", not how far along the highlight is.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_highlight_color(app: *const SyoApp) -> SyoColor {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return SyoColor {
            r: 0xff,
            g: 0xe0,
            b: 0x66,
            a: 140,
        };
    };
    app.highlight_color
}

/// Resolved starting directory for the Open dialog (absolute when known; empty
/// when even the launch directory is unavailable, in which case the shell lets
/// Qt choose). Free with `syo_string_free`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_open_dir(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    to_c_string(app.open_dir.clone())
}

/// Path of the open document, or an empty string when none is open. Free with
/// `syo_string_free`.
///
/// The shell needs it to name things after the document — the export file, a
/// window title — and asking here keeps the core the only place that knows
/// which file is open.
///
/// # Safety
/// `app` must be NULL or valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_document_path(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    to_c_string(
        app.app
            .document_path()
            .map(|p| p.display().to_string())
            .unwrap_or_default(),
    )
}

/// Human-readable provenance of the Open-dialog directory (e.g. "launch
/// directory", "config: files.open_dir (...)"), for `--check`. Free with
/// `syo_string_free`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_open_dir_source(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    to_c_string(app.open_dir_source.clone())
}

/// Free a string returned by this library.
///
/// # Safety
/// `s` must be NULL or a pointer returned by a syo_* function, not freed
/// before.
#[no_mangle]
pub unsafe extern "C" fn syo_string_free(s: *mut c_char) {
    if !s.is_null() {
        unsafe { drop(CString::from_raw(s)) };
    }
}

/// Version of the core library (the Rust workspace crate). Free with
/// `syo_string_free`. Reported by the shell's `--version`/`--check`.
#[no_mangle]
pub extern "C" fn syo_core_version() -> *mut c_char {
    to_c_string(env!("CARGO_PKG_VERSION").to_string())
}

/// Default config file path for this platform (may not exist yet).
/// Free with `syo_string_free`.
#[no_mangle]
pub extern "C" fn syo_default_config_path() -> *mut c_char {
    to_c_string(
        default_base_dir("XDG_CONFIG_HOME", ".config")
            .join("syodep")
            .join("config.toml")
            .display()
            .to_string(),
    )
}

/// Documented default configuration as TOML text: every option set to its
/// built-in default. Written to disk by the shell's `--defaults`. Free with
/// `syo_string_free`.
#[no_mangle]
pub extern "C" fn syo_default_config_toml() -> *mut c_char {
    to_c_string(syodep_config::default_config_doc())
}

/// Default database path for this platform. Free with `syo_string_free`.
#[no_mangle]
pub extern "C" fn syo_default_db_path() -> *mut c_char {
    to_c_string(
        default_base_dir("XDG_DATA_HOME", ".local/share")
            .join("syodep")
            .join("syodep.sqlite3")
            .display()
            .to_string(),
    )
}

/// Resolve a per-user base directory without extra dependencies.
/// Windows uses %APPDATA%; Unix follows the XDG spec with its fallbacks.
fn default_base_dir(xdg_var: &str, unix_fallback: &str) -> PathBuf {
    #[cfg(windows)]
    {
        let _ = (xdg_var, unix_fallback);
        if let Some(appdata) = std::env::var_os("APPDATA") {
            return PathBuf::from(appdata);
        }
        return PathBuf::from(".");
    }
    #[cfg(not(windows))]
    {
        if let Some(dir) = std::env::var_os(xdg_var) {
            let path = PathBuf::from(dir);
            if path.is_absolute() {
                return path;
            }
        }
        if let Some(home) = std::env::var_os("HOME") {
            return std::path::Path::new(&home).join(unix_fallback);
        }
        PathBuf::from(".")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CString;

    /// Exercise the full C surface the way the Qt shell does.
    #[test]
    fn ffi_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        let pdf_path = dir.path().join("doc.pdf");
        std::fs::write(
            &pdf_path,
            syodep_pdf::test_support::pdf_with_pages(&["alpha", "beta"]),
        )
        .unwrap();
        let db_path = CString::new(dir.path().join("db.sqlite3").display().to_string()).unwrap();

        unsafe {
            let app = syo_app_new(std::ptr::null(), db_path.as_ptr());
            assert!(!app.is_null());
            assert!(!syo_app_has_document(app));

            syo_app_set_viewport(app, 595.0, 600.0);
            let c_pdf = CString::new(pdf_path.display().to_string()).unwrap();
            assert!(syo_app_open_document(app, c_pdf.as_ptr()));
            assert!(syo_app_has_document(app));

            // Status text mentions the file and page count.
            let status = syo_app_status_text(app);
            let text = CStr::from_ptr(status).to_str().unwrap().to_owned();
            syo_string_free(status);
            assert!(text.contains("doc.pdf"), "{text}");
            assert!(text.contains("[1/2]"), "{text}");

            // Key events: scroll, then quit (`<leader>q`, a two-key sequence:
            // no highlights, so it quits immediately with no confirmation).
            let j = CString::new("j").unwrap();
            assert_eq!(syo_app_key_event(app, j.as_ptr()), SYO_EFFECT_REDRAW);
            let leader = CString::new("<Space>").unwrap();
            let q = CString::new("q").unwrap();
            syo_app_key_event(app, leader.as_ptr());
            let quit_bits = syo_app_key_event(app, q.as_ptr());
            assert_eq!(quit_bits & SYO_EFFECT_QUIT, SYO_EFFECT_QUIT);
            assert_eq!(quit_bits & SYO_EFFECT_CONFIRM_QUIT, 0);

            // Visible pages.
            let mut pages = [SyoVisiblePage {
                page: 0,
                x: 0.0,
                y: 0.0,
                width: 0.0,
                height: 0.0,
            }; 8];
            let count = syo_app_visible_pages(app, pages.as_mut_ptr(), pages.len());
            assert!(count >= 1);
            assert_eq!(pages[0].page, 0);

            // Render.
            let bitmap = syo_app_render_page(app, 0);
            assert!(!bitmap.is_null());
            assert_eq!((*bitmap).width, 595);
            assert!(!(*bitmap).data.is_null());
            syo_bitmap_free(bitmap);

            // Focus mode: inactive until entered, then valid at every scope.
            // One getter covers all five, so the round-trip walks the scope
            // letters rather than five different functions.
            let f_key = CString::new("f").unwrap();
            let esc = CString::new("<Esc>").unwrap();
            let focus = syo_app_focus(app);
            assert_eq!(focus.valid, 0);
            syo_overlay_free(focus);
            // `fc` is a two-key sequence: one `f` is pending, `c` enters char scope.
            syo_app_key_event(app, f_key.as_ptr());
            let pending = syo_app_focus(app);
            assert_eq!(pending.valid, 0);
            syo_overlay_free(pending);
            let c_scope = CString::new("c").unwrap();
            syo_app_key_event(app, c_scope.as_ptr());
            let char_scope = syo_app_focus(app);
            assert_eq!(char_scope.valid, 1);
            assert_eq!(char_scope.rect_count, 1);
            let first_x = (*char_scope.rects).x;
            syo_overlay_free(char_scope);

            // Moving right does not move the highlight left.
            let l_key = CString::new("l").unwrap();
            syo_app_key_event(app, l_key.as_ptr());
            let moved = syo_app_focus(app);
            assert_eq!(moved.valid, 1);
            assert!((*moved.rects).x >= first_x);
            syo_overlay_free(moved);

            // Every other scope, entered with `f` plus its letter. `e` rather
            // than `l` for lines: `l` is the forward motion in every mode.
            for letter in ["w", "e", "s", "p"] {
                let key = CString::new(letter).unwrap();
                syo_app_key_event(app, f_key.as_ptr());
                syo_app_key_event(app, key.as_ptr());
                let overlay = syo_app_focus(app);
                assert_eq!(overlay.valid, 1, "scope {letter} produced no overlay");
                assert!(overlay.rect_count >= 1);
                syo_overlay_free(overlay);
            }

            // Leaving focus mode hides the overlay again.
            syo_app_key_event(app, esc.as_ptr());
            let hidden = syo_app_focus(app);
            assert_eq!(hidden.valid, 0);
            // Freeing an invalid overlay is a no-op, so the shell can call it
            // unconditionally.
            syo_overlay_free(hidden);

            // Visual mode: inactive until entered with `vw`, then valid with at
            // least one rect; the rect buffer must be freed.
            let v_key = CString::new("v").unwrap();
            let w_key = CString::new("w").unwrap();
            let none = syo_app_selection(app);
            assert_eq!(none.valid, 0);
            syo_overlay_free(none);
            syo_app_key_event(app, v_key.as_ptr());
            syo_app_key_event(app, w_key.as_ptr());
            let selection = syo_app_selection(app);
            assert_eq!(selection.valid, 1);
            assert!(selection.rect_count >= 1);
            syo_overlay_free(selection);
            // Growing the selection keeps it valid.
            syo_app_key_event(app, l_key.as_ptr());
            let grown = syo_app_selection(app);
            assert_eq!(grown.valid, 1);
            syo_overlay_free(grown);
            syo_app_key_event(app, esc.as_ptr());
            let gone = syo_app_selection(app);
            assert_eq!(gone.valid, 0);
            syo_overlay_free(gone);

            // Out-of-range render fails cleanly.
            let bad = syo_app_render_page(app, 99);
            assert!(bad.is_null());

            syo_app_free(app);
        }
    }

    /// The quit-confirmation surface: the query flips true once a highlight
    /// is committed, and each answer function does what it says.
    #[test]
    fn quit_confirmation_surface() {
        let dir = tempfile::tempdir().unwrap();
        let pdf_path = dir.path().join("doc.pdf");
        std::fs::write(
            &pdf_path,
            syodep_pdf::test_support::pdf_with_pages(&["alpha beta gamma"]),
        )
        .unwrap();
        let commit_highlight = |app: *mut SyoApp| unsafe {
            for key in ["f", "w", "a", "a"] {
                let c_key = CString::new(key).unwrap();
                syo_app_key_event(app, c_key.as_ptr());
            }
        };

        unsafe {
            // Discard & Quit.
            let db_path =
                CString::new(dir.path().join("discard.sqlite3").display().to_string()).unwrap();
            let app = syo_app_new(std::ptr::null(), db_path.as_ptr());
            syo_app_set_viewport(app, 595.0, 600.0);
            let c_pdf = CString::new(pdf_path.display().to_string()).unwrap();
            assert!(syo_app_open_document(app, c_pdf.as_ptr()));

            assert!(!syo_app_has_unsaved_highlights(app));
            commit_highlight(app);
            assert!(syo_app_has_unsaved_highlights(app));

            let bits = syo_app_quit_discard(app);
            assert_eq!(bits & SYO_EFFECT_QUIT, SYO_EFFECT_QUIT);
            syo_app_free(app);

            // Save & Quit.
            let db_path =
                CString::new(dir.path().join("save.sqlite3").display().to_string()).unwrap();
            let app = syo_app_new(std::ptr::null(), db_path.as_ptr());
            syo_app_set_viewport(app, 595.0, 600.0);
            assert!(syo_app_open_document(app, c_pdf.as_ptr()));

            commit_highlight(app);
            assert!(syo_app_has_unsaved_highlights(app));

            let bits = syo_app_quit_save(app);
            assert_eq!(bits & SYO_EFFECT_QUIT, SYO_EFFECT_QUIT);
            assert!(!syo_app_has_unsaved_highlights(app));
            syo_app_free(app);
        }
    }

    #[test]
    fn null_arguments_are_tolerated() {
        unsafe {
            assert!(!syo_app_open_document(
                std::ptr::null_mut(),
                std::ptr::null()
            ));
            assert_eq!(syo_app_key_event(std::ptr::null_mut(), std::ptr::null()), 0);
            assert_eq!(
                syo_app_visible_pages(std::ptr::null(), std::ptr::null_mut(), 0),
                0
            );
            syo_bitmap_free(std::ptr::null_mut());
            syo_string_free(std::ptr::null_mut());
            syo_app_free(std::ptr::null_mut());
        }
    }

    #[test]
    fn bad_config_becomes_warning_not_failure() {
        let dir = tempfile::tempdir().unwrap();
        let config_path = dir.path().join("config.toml");
        std::fs::write(&config_path, "this is [[ not toml").unwrap();
        let c_config = CString::new(config_path.display().to_string()).unwrap();
        unsafe {
            let app = syo_app_new(c_config.as_ptr(), std::ptr::null());
            assert!(!app.is_null());
            let status = syo_app_status_text(app);
            let text = CStr::from_ptr(status).to_str().unwrap().to_owned();
            syo_string_free(status);
            assert!(text.contains("default config"), "{text}");
            syo_app_free(app);
        }
    }

    #[test]
    fn resolve_open_dir_defaults_to_cwd() {
        let cwd = std::env::current_dir().unwrap().display().to_string();
        let r = resolve_open_dir(None);
        assert_eq!(r.path, cwd);
        assert_eq!(r.source, "launch directory");
        assert!(r.warning.is_none());

        // An empty / whitespace override is treated as unset.
        let r = resolve_open_dir(Some("   "));
        assert_eq!(r.path, cwd);
        assert!(r.warning.is_none());
    }

    #[test]
    fn resolve_open_dir_uses_existing_configured_dir() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().display().to_string();
        let r = resolve_open_dir(Some(&path));
        assert_eq!(r.path, path);
        assert!(r.source.contains("files.open_dir"));
        assert!(r.warning.is_none());
    }

    #[test]
    fn resolve_open_dir_falls_back_when_configured_dir_missing() {
        let cwd = std::env::current_dir().unwrap().display().to_string();
        let r = resolve_open_dir(Some("/no/such/syodep/dir"));
        assert_eq!(r.path, cwd);
        assert!(r.source.contains("not found"));
        assert!(r.warning.is_some());
    }

    #[test]
    fn color_getters_wire_through_config() {
        let dir = tempfile::tempdir().unwrap();
        let config_path = dir.path().join("config.toml");
        std::fs::write(
            &config_path,
            "[view]\n\
             background = '#102030'\n\
             focus_color = '#405060'\n\
             focus_opacity = 1.0\n\
             visual_color = '#708090'\n\
             visual_opacity = 0.0\n\
             highlight_color = '#a0b0c0'\n\
             highlight_opacity = 0.5\n",
        )
        .unwrap();
        let c_config = CString::new(config_path.display().to_string()).unwrap();
        unsafe {
            let app = syo_app_new(c_config.as_ptr(), std::ptr::null());
            assert!(!app.is_null());

            let bg = syo_app_background_color(app);
            assert_eq!((bg.r, bg.g, bg.b), (0x10, 0x20, 0x30));
            assert_eq!(bg.a, 255, "the background is always opaque");

            let focus = syo_app_focus_color(app);
            assert_eq!((focus.r, focus.g, focus.b), (0x40, 0x50, 0x60));
            assert_eq!(focus.a, 255, "opacity 1.0 maps to a fully opaque alpha");

            let visual = syo_app_visual_color(app);
            assert_eq!((visual.r, visual.g, visual.b), (0x70, 0x80, 0x90));
            assert_eq!(visual.a, 0, "opacity 0.0 maps to a fully transparent alpha");

            let highlight = syo_app_highlight_color(app);
            assert_eq!((highlight.r, highlight.g, highlight.b), (0xa0, 0xb0, 0xc0));
            assert_eq!(highlight.a, 128);

            syo_app_free(app);
        }
    }

    #[test]
    fn the_highlight_overlay_is_empty_without_a_document() {
        unsafe {
            let app = syo_app_new(std::ptr::null(), std::ptr::null());
            let overlay = syo_app_highlights(app);
            assert_eq!(overlay.valid, 0);
            syo_overlay_free(overlay);
            syo_app_free(app);
        }
    }

    #[test]
    fn invalid_color_falls_back_and_warns() {
        let dir = tempfile::tempdir().unwrap();
        let config_path = dir.path().join("config.toml");
        std::fs::write(&config_path, "[view]\nfocus_color = 'not a colour'\n").unwrap();
        let c_config = CString::new(config_path.display().to_string()).unwrap();
        unsafe {
            let app = syo_app_new(c_config.as_ptr(), std::ptr::null());
            assert!(!app.is_null());
            // Falls back to the built-in blue rather than rendering nothing,
            // and says so.
            let focus = syo_app_focus_color(app);
            assert_eq!((focus.r, focus.g, focus.b), (0x5b, 0x9b, 0xd5));
            // The fallback surfaces in the status line, like the open_dir
            // warning -- report_error feeds status_text, not startup_warnings
            // (which carries keymap errors).
            let status = syo_app_status_text(app);
            let text = CStr::from_ptr(status).to_str().unwrap().to_owned();
            syo_string_free(status);
            assert!(text.contains("focus_color"), "{text}");
            syo_app_free(app);
        }
    }

    #[test]
    fn opacity_out_of_range_is_clamped() {
        let dir = tempfile::tempdir().unwrap();
        let config_path = dir.path().join("config.toml");
        std::fs::write(
            &config_path,
            "[view]\nfocus_opacity = 9.0\nvisual_opacity = -3.0\n",
        )
        .unwrap();
        let c_config = CString::new(config_path.display().to_string()).unwrap();
        unsafe {
            let app = syo_app_new(c_config.as_ptr(), std::ptr::null());
            assert_eq!(syo_app_focus_color(app).a, 255);
            assert_eq!(syo_app_visual_color(app).a, 0);
            syo_app_free(app);
        }
    }

    #[test]
    fn open_dir_getters_wire_through_config() {
        let dir = tempfile::tempdir().unwrap();
        let config_path = dir.path().join("config.toml");
        let papers = dir.path().join("papers");
        std::fs::create_dir(&papers).unwrap();
        // TOML literal string (single quotes) so Windows backslash paths are
        // not mangled by basic-string escape processing.
        std::fs::write(
            &config_path,
            format!("[files]\nopen_dir = '{}'\n", papers.display()),
        )
        .unwrap();
        let c_config = CString::new(config_path.display().to_string()).unwrap();
        unsafe {
            let app = syo_app_new(c_config.as_ptr(), std::ptr::null());
            assert!(!app.is_null());
            let open = syo_app_open_dir(app);
            let open_s = CStr::from_ptr(open).to_str().unwrap().to_owned();
            syo_string_free(open);
            assert_eq!(open_s, papers.display().to_string());
            let src = syo_app_open_dir_source(app);
            let src_s = CStr::from_ptr(src).to_str().unwrap().to_owned();
            syo_string_free(src);
            assert!(src_s.contains("files.open_dir"), "{src_s}");
            syo_app_free(app);
        }
    }

    #[test]
    fn missing_open_dir_warns_and_falls_back() {
        let dir = tempfile::tempdir().unwrap();
        let config_path = dir.path().join("config.toml");
        std::fs::write(
            &config_path,
            "[files]\nopen_dir = \"/no/such/syodep/dir\"\n",
        )
        .unwrap();
        let c_config = CString::new(config_path.display().to_string()).unwrap();
        let cwd = std::env::current_dir().unwrap().display().to_string();
        unsafe {
            let app = syo_app_new(c_config.as_ptr(), std::ptr::null());
            assert!(!app.is_null());
            let open = syo_app_open_dir(app);
            let open_s = CStr::from_ptr(open).to_str().unwrap().to_owned();
            syo_string_free(open);
            assert_eq!(open_s, cwd);
            // The fallback surfaces in the status line.
            let status = syo_app_status_text(app);
            let text = CStr::from_ptr(status).to_str().unwrap().to_owned();
            syo_string_free(status);
            assert!(text.contains("open_dir not found"), "{text}");
            syo_app_free(app);
        }
    }

    #[test]
    fn default_paths_are_nonempty() {
        unsafe {
            let config = syo_default_config_path();
            let db = syo_default_db_path();
            assert!(!CStr::from_ptr(config).to_str().unwrap().is_empty());
            assert!(CStr::from_ptr(db).to_str().unwrap().contains("syodep"));
            syo_string_free(config);
            syo_string_free(db);
        }
    }

    #[test]
    fn highlight_list_api_round_trips() {
        use std::ffi::CStr;
        let dir = tempfile::tempdir().unwrap();
        let pdf_path = dir.path().join("doc.pdf");
        std::fs::write(
            &pdf_path,
            syodep_pdf::test_support::pdf_with_pages(&["alpha beta gamma"]),
        )
        .unwrap();
        let db_path = CString::new(dir.path().join("db.sqlite3").display().to_string()).unwrap();
        let commit_highlight = |app: *mut SyoApp| unsafe {
            for key in ["f", "w", "a", "a"] {
                let c_key = CString::new(key).unwrap();
                syo_app_key_event(app, c_key.as_ptr());
            }
        };

        unsafe {
            // Empty list with no document; freeing null is a no-op.
            let empty_app = syo_app_new(std::ptr::null(), std::ptr::null());
            let empty = syo_app_highlight_list(empty_app);
            assert!(!empty.is_null());
            assert_eq!((*empty).count, 0);
            assert!((*empty).items.is_null());
            syo_highlight_list_free(empty);
            syo_highlight_list_free(std::ptr::null_mut());
            syo_app_free(empty_app);

            let app = syo_app_new(std::ptr::null(), db_path.as_ptr());
            syo_app_set_viewport(app, 595.0, 600.0);
            let c_pdf = CString::new(pdf_path.display().to_string()).unwrap();
            assert!(syo_app_open_document(app, c_pdf.as_ptr()));
            let rev_before = syo_app_annotation_revision(app);

            commit_highlight(app);
            assert!(syo_app_has_unsaved_highlights(app));

            let list = syo_app_highlight_list(app);
            assert_eq!((*list).count, 1);
            assert!((*list).revision > rev_before);
            let item = &*(*list).items;
            assert!(item.id > 0);
            assert_eq!(item.first_page, 0);
            assert_eq!(item.last_page, 0);
            assert_eq!(item.state, SYO_HIGHLIGHT_PENDING);
            assert_eq!(CStr::from_ptr(item.text).to_str().unwrap(), "alpha");
            assert!(!CStr::from_ptr(item.color).to_str().unwrap().is_empty());
            let id = item.id;
            syo_highlight_list_free(list);

            let mut effects = 1u32;
            assert!(!syo_app_delete_highlight(app, 999_999, &mut effects));
            assert_eq!(effects, 0, "an unknown id changes nothing");
            let list = syo_app_highlight_list(app);
            assert_eq!((*list).count, 1);
            syo_highlight_list_free(list);

            let md = syo_app_highlight_markdown(app, id);
            assert!(!md.is_null());
            let md_s = CStr::from_ptr(md).to_str().unwrap().to_owned();
            syo_string_free(md);
            assert_eq!(md_s, "## Page 1\n\n> alpha");

            let all = syo_app_all_highlights_markdown(app);
            let all_s = CStr::from_ptr(all).to_str().unwrap().to_owned();
            syo_string_free(all);
            assert_eq!(all_s, format!("# Highlights\n\n{md_s}"));
            assert!(syo_app_highlight_markdown(app, 999_999).is_null());

            let reveal_bits = syo_app_reveal_highlight(app, id);
            assert_eq!(reveal_bits & SYO_EFFECT_REDRAW, SYO_EFFECT_REDRAW);

            let space = CString::new("<Space>").unwrap();
            syo_app_key_event(app, space.as_ptr());
            let w_key = CString::new("w").unwrap();
            let save_bits = syo_app_key_event(app, w_key.as_ptr());
            assert_eq!(
                save_bits & SYO_EFFECT_ANNOTATIONS_CHANGED,
                SYO_EFFECT_ANNOTATIONS_CHANGED
            );
            assert!(!syo_app_has_unsaved_highlights(app));

            let list = syo_app_highlight_list(app);
            assert_eq!((*list).count, 1);
            assert_eq!((*(*list).items).state, SYO_HIGHLIGHT_EMBEDDED);
            syo_highlight_list_free(list);

            // Deleting the Embedded highlight takes the PDF annotation with
            // it, so the file is rewritten and the shell must drop its bitmaps.
            effects = 0;
            assert!(syo_app_delete_highlight(app, id, &mut effects));
            assert_eq!(
                effects & SYO_EFFECT_ANNOTATIONS_CHANGED,
                SYO_EFFECT_ANNOTATIONS_CHANGED
            );
            assert_eq!(effects & SYO_EFFECT_RELOAD, SYO_EFFECT_RELOAD);
            let list = syo_app_highlight_list(app);
            assert_eq!((*list).count, 0);
            syo_highlight_list_free(list);
            assert!(syodep_pdf::page_highlight_names(&pdf_path, 0)
                .unwrap()
                .is_empty());

            syo_app_free(app);
        }
    }

    #[test]
    fn annotation_api_survives_null_app() {
        unsafe {
            assert_eq!(syo_app_annotation_revision(std::ptr::null()), 0);
            assert_eq!(syo_app_reveal_highlight(std::ptr::null_mut(), 1), 0);
            assert!(syo_app_highlight_markdown(std::ptr::null(), 1).is_null());
            let all = syo_app_all_highlights_markdown(std::ptr::null());
            assert_eq!(CStr::from_ptr(all).to_str().unwrap(), "");
            syo_string_free(all);
            let mut effects = 99u32;
            assert!(!syo_app_delete_highlight(
                std::ptr::null_mut(),
                1,
                &mut effects
            ));
            assert_eq!(effects, 0);
            let list = syo_app_highlight_list(std::ptr::null());
            assert_eq!((*list).count, 0);
            syo_highlight_list_free(list);
            let path = syo_app_document_path(std::ptr::null());
            assert_eq!(CStr::from_ptr(path).to_str().unwrap(), "");
            syo_string_free(path);
        }
    }

    #[test]
    fn the_sidebar_toggle_reaches_the_shell_as_its_own_bit() {
        // The bit is the whole contract: the core has no idea whether the
        // sidebar is open, so a wrong or missing bit is a silently dead
        // keybinding rather than a visible failure.
        unsafe {
            let app = syo_app_new(std::ptr::null(), std::ptr::null());
            let leader = CString::new("<Space>").unwrap();
            let a = CString::new("a").unwrap();
            syo_app_key_event(app, leader.as_ptr());
            let bits = syo_app_key_event(app, a.as_ptr());
            assert_eq!(
                bits & SYO_EFFECT_TOGGLE_HIGHLIGHTS_SIDEBAR,
                SYO_EFFECT_TOGGLE_HIGHLIGHTS_SIDEBAR
            );
            assert_eq!(bits & SYO_EFFECT_QUIT, 0);
            syo_app_free(app);
        }
    }
}
