//! C ABI for the syodep core, consumed by the Qt shell.
//!
//! Conventions:
//!
//! - Every function is `extern "C"` and panic-safe (panics are caught and
//!   reported as errors / no-ops rather than unwinding into C++).
//! - The shell owns one `SyoApp` per window, created with [`syo_app_new`]
//!   and destroyed with [`syo_app_free`].
//! - Strings returned by the core are freed with [`syo_string_free`];
//!   bitmaps with [`syo_bitmap_free`]. Strings passed in are borrowed UTF-8.
//! - Key events arrive as the textual chord syntax from
//!   `syodep_config::keys` (e.g. `j`, `G`, `<C-d>`); the shell performs the
//!   purely mechanical Qt-event-to-string translation.
//!
//! The header `include/syodep_ffi.h` is generated by cbindgen at build time.
//!
//! Safety: this crate is the FFI boundary; all `unsafe` here is confined to
//! pointer/CString handling at the very edge. No MuPDF or Qt types cross
//! this boundary in either direction.

use std::ffi::{c_char, CStr, CString};
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::path::PathBuf;

use syodep_config::keys::parse_sequence;
use syodep_config::Config;
use syodep_core::{App, Effects};
use syodep_storage::Storage;

/// Opaque application handle.
pub struct SyoApp {
    app: App,
    /// Resolved starting directory for the Open dialog (absolute when known).
    open_dir: String,
    /// Human-readable provenance of `open_dir`, reported by `--check`.
    open_dir_source: String,
}

/// Outcome of resolving the Open-dialog starting directory.
struct OpenDirResolution {
    /// Directory the dialog should open in (empty if even the CWD is unknown,
    /// in which case the shell lets Qt pick its own default).
    path: String,
    /// Short note on where the value came from, for `--check`.
    source: String,
    /// A startup warning to surface, set only when a configured directory was
    /// requested but could not be used.
    warning: Option<String>,
}

/// Resolve the Open-dialog starting directory.
///
/// Precedence: a configured `files.open_dir` that exists as a directory wins;
/// otherwise the launch (current working) directory is used. A configured path
/// that is missing or not a directory falls back to the launch directory and
/// produces a warning.
fn resolve_open_dir(configured: Option<&str>) -> OpenDirResolution {
    let cwd = std::env::current_dir()
        .ok()
        .map(|p| p.display().to_string())
        .unwrap_or_default();

    match configured {
        Some(raw) if !raw.trim().is_empty() => {
            if PathBuf::from(raw).is_dir() {
                OpenDirResolution {
                    path: raw.to_owned(),
                    source: format!("config: files.open_dir ({raw})"),
                    warning: None,
                }
            } else {
                OpenDirResolution {
                    path: cwd,
                    source: format!("config dir not found ({raw}) — using launch directory"),
                    warning: Some(format!(
                        "open_dir not found: {raw} — using launch directory"
                    )),
                }
            }
        }
        _ => OpenDirResolution {
            path: cwd,
            source: "launch directory".to_owned(),
            warning: None,
        },
    }
}

/// Effect bits returned by input functions.
pub const SYO_EFFECT_REDRAW: u32 = 1;
pub const SYO_EFFECT_QUIT: u32 = 2;
pub const SYO_EFFECT_OPEN_FILE_DIALOG: u32 = 4;

fn effects_to_bits(effects: Effects) -> u32 {
    let mut bits = 0;
    if effects.redraw {
        bits |= SYO_EFFECT_REDRAW;
    }
    if effects.quit {
        bits |= SYO_EFFECT_QUIT;
    }
    if effects.open_file_dialog {
        bits |= SYO_EFFECT_OPEN_FILE_DIALOG;
    }
    bits
}

/// A page to draw, in canvas pixel coordinates.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SyoVisiblePage {
    pub page: usize,
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

/// The caret rectangle in canvas pixels, for the overlay the shell paints.
/// `valid` is 0 when not in caret focus mode or no caret is placed, in which case
/// the remaining fields are unspecified.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SyoCaret {
    pub valid: u8,
    pub page: usize,
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

/// A tightly packed RGBA8 image (stride = width * 4).
#[repr(C)]
pub struct SyoBitmap {
    pub width: u32,
    pub height: u32,
    pub data: *mut u8,
    pub data_len: usize,
}

unsafe fn cstr_to_path(ptr: *const c_char) -> Option<PathBuf> {
    if ptr.is_null() {
        return None;
    }
    let s = unsafe { CStr::from_ptr(ptr) }.to_str().ok()?;
    Some(PathBuf::from(s))
}

fn to_c_string(s: String) -> *mut c_char {
    // Interior NULs cannot come from our own status/error strings, but be
    // defensive at the boundary.
    CString::new(s.replace('\0', " "))
        .expect("NUL bytes were just stripped")
        .into_raw()
}

/// Create the application core.
///
/// `config_path` and `db_path` may be NULL: a NULL config uses built-in
/// defaults, a NULL database path disables persistence. A config file that
/// fails to parse is reported as a startup warning (see
/// `syo_app_take_warnings`) and replaced by defaults; it never aborts.
///
/// # Safety
/// `config_path` and `db_path` must be NULL or valid NUL-terminated strings.
#[no_mangle]
pub unsafe extern "C" fn syo_app_new(
    config_path: *const c_char,
    db_path: *const c_char,
) -> *mut SyoApp {
    let config_path = unsafe { cstr_to_path(config_path) };
    let db_path = unsafe { cstr_to_path(db_path) };
    let result = catch_unwind(|| {
        let mut warnings = Vec::new();
        let config = match &config_path {
            Some(path) => match Config::load(path) {
                Ok(config) => config,
                Err(e) => {
                    warnings.push(format!("using default config: {e}"));
                    Config::default()
                }
            },
            None => Config::default(),
        };
        let storage = match &db_path {
            Some(path) => match Storage::open(path) {
                Ok(storage) => Some(storage),
                Err(e) => {
                    warnings.push(format!("persistence disabled: {e}"));
                    None
                }
            },
            None => None,
        };
        let open = resolve_open_dir(config.files.open_dir.as_deref());
        if let Some(warning) = open.warning {
            warnings.push(warning);
        }
        let mut app = App::new(config, storage);
        for warning in warnings {
            app.report_error(warning);
        }
        SyoApp {
            app,
            open_dir: open.path,
            open_dir_source: open.source,
        }
    });
    match result {
        Ok(app) => Box::into_raw(Box::new(app)),
        Err(_) => std::ptr::null_mut(),
    }
}

/// Destroy the application core, persisting the reading position.
///
/// # Safety
/// `app` must be a pointer returned by `syo_app_new`, not freed before.
#[no_mangle]
pub unsafe extern "C" fn syo_app_free(app: *mut SyoApp) {
    if !app.is_null() {
        let boxed = unsafe { Box::from_raw(app) };
        let _ = catch_unwind(AssertUnwindSafe(move || drop(boxed)));
    }
}

/// Open a document. Returns true on success; on failure the previous
/// document (if any) stays open and the error is shown in the status text.
///
/// # Safety
/// `app` must be valid; `path` must be a valid NUL-terminated string.
#[no_mangle]
pub unsafe extern "C" fn syo_app_open_document(app: *mut SyoApp, path: *const c_char) -> bool {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return false;
    };
    let Some(path) = (unsafe { cstr_to_path(path) }) else {
        return false;
    };
    catch_unwind(AssertUnwindSafe(|| match app.app.open_document(&path) {
        Ok(()) => true,
        Err(e) => {
            app.app.report_error(e.to_string());
            false
        }
    }))
    .unwrap_or(false)
}

/// True when a document is open.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_has_document(app: *const SyoApp) -> bool {
    unsafe { app.as_ref() }
        .map(|a| a.app.has_document())
        .unwrap_or(false)
}

/// Inform the core of the canvas size in physical pixels.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_set_viewport(app: *mut SyoApp, width: f32, height: f32) {
    if let Some(app) = unsafe { app.as_mut() } {
        let _ = catch_unwind(AssertUnwindSafe(|| {
            app.app.set_viewport_size(width, height)
        }));
    }
}

/// Feed one key chord (textual syntax, e.g. "j", "G", "<C-d>", "<Esc>").
/// Returns SYO_EFFECT_* bits.
///
/// # Safety
/// `app` must be valid; `key` must be a valid NUL-terminated string.
#[no_mangle]
pub unsafe extern "C" fn syo_app_key_event(app: *mut SyoApp, key: *const c_char) -> u32 {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return 0;
    };
    if key.is_null() {
        return 0;
    }
    let Ok(key) = (unsafe { CStr::from_ptr(key) }).to_str() else {
        return 0;
    };
    catch_unwind(AssertUnwindSafe(|| {
        match parse_sequence(key).as_deref() {
            // The shell sends exactly one chord per key event.
            Ok([chord]) => effects_to_bits(app.app.handle_key(*chord)),
            _ => 0,
        }
    }))
    .unwrap_or(0)
}

/// Scroll by a pixel delta (mouse wheel). Returns SYO_EFFECT_* bits.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_scroll_by(app: *mut SyoApp, dx: f32, dy: f32) -> u32 {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return 0;
    };
    catch_unwind(AssertUnwindSafe(|| {
        effects_to_bits(app.app.scroll_by_px(dx, dy))
    }))
    .unwrap_or(0)
}

/// Fill `out` with up to `capacity` visible pages; returns the number of
/// visible pages (which may exceed `capacity`; call again with more room).
///
/// # Safety
/// `app` must be valid; `out` must point to at least `capacity` elements.
#[no_mangle]
pub unsafe extern "C" fn syo_app_visible_pages(
    app: *const SyoApp,
    out: *mut SyoVisiblePage,
    capacity: usize,
) -> usize {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return 0;
    };
    let Ok(pages) = catch_unwind(AssertUnwindSafe(|| app.app.visible_pages())) else {
        return 0;
    };
    if !out.is_null() {
        for (i, page) in pages.iter().take(capacity).enumerate() {
            unsafe {
                *out.add(i) = SyoVisiblePage {
                    page: page.page,
                    x: page.rect.x,
                    y: page.rect.y,
                    width: page.rect.width,
                    height: page.rect.height,
                };
            }
        }
    }
    pages.len()
}

/// The caret rectangle (canvas pixels) for the overlay. When `valid` is 0 the
/// shell draws nothing.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_caret(app: *const SyoApp) -> SyoCaret {
    let invalid = SyoCaret {
        valid: 0,
        page: 0,
        x: 0.0,
        y: 0.0,
        width: 0.0,
        height: 0.0,
    };
    let Some(app) = (unsafe { app.as_ref() }) else {
        return invalid;
    };
    catch_unwind(AssertUnwindSafe(|| match app.app.caret_screen_rect() {
        Some((page, rect)) => SyoCaret {
            valid: 1,
            page,
            x: rect.x,
            y: rect.y,
            width: rect.width,
            height: rect.height,
        },
        None => invalid,
    }))
    .unwrap_or(invalid)
}

/// The line-focus rectangle (canvas pixels) for the overlay. Reuses the
/// [`SyoCaret`] layout; `valid` is 0 unless line focus mode is active with a
/// line marked.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_line(app: *const SyoApp) -> SyoCaret {
    let invalid = SyoCaret {
        valid: 0,
        page: 0,
        x: 0.0,
        y: 0.0,
        width: 0.0,
        height: 0.0,
    };
    let Some(app) = (unsafe { app.as_ref() }) else {
        return invalid;
    };
    catch_unwind(AssertUnwindSafe(|| match app.app.line_screen_rect() {
        Some((page, rect)) => SyoCaret {
            valid: 1,
            page,
            x: rect.x,
            y: rect.y,
            width: rect.width,
            height: rect.height,
        },
        None => invalid,
    }))
    .unwrap_or(invalid)
}

/// Render a page at the current zoom. Returns NULL on failure. The result
/// must be freed with `syo_bitmap_free`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_render_page(app: *mut SyoApp, page: usize) -> *mut SyoBitmap {
    let Some(app) = (unsafe { app.as_mut() }) else {
        return std::ptr::null_mut();
    };
    if !app.app.has_document() {
        return std::ptr::null_mut();
    }
    let result = catch_unwind(AssertUnwindSafe(|| match app.app.render_page(page) {
        Ok(bitmap) => {
            let mut data = bitmap.data.clone().into_boxed_slice();
            let out = SyoBitmap {
                width: bitmap.width,
                height: bitmap.height,
                data: data.as_mut_ptr(),
                data_len: data.len(),
            };
            std::mem::forget(data);
            Box::into_raw(Box::new(out))
        }
        Err(e) => {
            app.app.report_error(e.to_string());
            std::ptr::null_mut()
        }
    }));
    result.unwrap_or(std::ptr::null_mut())
}

/// Free a bitmap returned by `syo_app_render_page`.
///
/// # Safety
/// `bitmap` must be NULL or a pointer returned by `syo_app_render_page`,
/// not freed before.
#[no_mangle]
pub unsafe extern "C" fn syo_bitmap_free(bitmap: *mut SyoBitmap) {
    if bitmap.is_null() {
        return;
    }
    unsafe {
        let bitmap = Box::from_raw(bitmap);
        if !bitmap.data.is_null() {
            drop(Box::from_raw(std::ptr::slice_from_raw_parts_mut(
                bitmap.data,
                bitmap.data_len,
            )));
        }
    }
}

/// Status line text. Free with `syo_string_free`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_status_text(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    let text = catch_unwind(AssertUnwindSafe(|| app.app.status_text())).unwrap_or_default();
    to_c_string(text)
}

/// Startup warnings (bad config entries etc.), newline-separated; empty
/// string when there are none. Free with `syo_string_free`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_startup_warnings(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    let text = catch_unwind(AssertUnwindSafe(|| app.app.startup_warnings().join("\n")))
        .unwrap_or_default();
    to_c_string(text)
}

/// Resolved starting directory for the Open dialog (absolute when known; empty
/// when even the launch directory is unavailable, in which case the shell lets
/// Qt choose). Free with `syo_string_free`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_open_dir(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    to_c_string(app.open_dir.clone())
}

/// Human-readable provenance of the Open-dialog directory (e.g. "launch
/// directory", "config: files.open_dir (...)"), for `--check`. Free with
/// `syo_string_free`.
///
/// # Safety
/// `app` must be valid.
#[no_mangle]
pub unsafe extern "C" fn syo_app_open_dir_source(app: *const SyoApp) -> *mut c_char {
    let Some(app) = (unsafe { app.as_ref() }) else {
        return to_c_string(String::new());
    };
    to_c_string(app.open_dir_source.clone())
}

/// Free a string returned by this library.
///
/// # Safety
/// `s` must be NULL or a pointer returned by a syo_* function, not freed
/// before.
#[no_mangle]
pub unsafe extern "C" fn syo_string_free(s: *mut c_char) {
    if !s.is_null() {
        unsafe { drop(CString::from_raw(s)) };
    }
}

/// Version of the core library (the Rust workspace crate). Free with
/// `syo_string_free`. Reported by the shell's `--version`/`--check`.
#[no_mangle]
pub extern "C" fn syo_core_version() -> *mut c_char {
    to_c_string(env!("CARGO_PKG_VERSION").to_string())
}

/// Default config file path for this platform (may not exist yet).
/// Free with `syo_string_free`.
#[no_mangle]
pub extern "C" fn syo_default_config_path() -> *mut c_char {
    to_c_string(
        default_base_dir("XDG_CONFIG_HOME", ".config")
            .join("syodep")
            .join("config.toml")
            .display()
            .to_string(),
    )
}

/// Default database path for this platform. Free with `syo_string_free`.
#[no_mangle]
pub extern "C" fn syo_default_db_path() -> *mut c_char {
    to_c_string(
        default_base_dir("XDG_DATA_HOME", ".local/share")
            .join("syodep")
            .join("syodep.sqlite3")
            .display()
            .to_string(),
    )
}

/// Resolve a per-user base directory without extra dependencies.
/// Windows uses %APPDATA%; Unix follows the XDG spec with its fallbacks.
fn default_base_dir(xdg_var: &str, unix_fallback: &str) -> PathBuf {
    #[cfg(windows)]
    {
        let _ = (xdg_var, unix_fallback);
        if let Some(appdata) = std::env::var_os("APPDATA") {
            return PathBuf::from(appdata);
        }
        return PathBuf::from(".");
    }
    #[cfg(not(windows))]
    {
        if let Some(dir) = std::env::var_os(xdg_var) {
            let path = PathBuf::from(dir);
            if path.is_absolute() {
                return path;
            }
        }
        if let Some(home) = std::env::var_os("HOME") {
            return std::path::Path::new(&home).join(unix_fallback);
        }
        PathBuf::from(".")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CString;

    /// Exercise the full C surface the way the Qt shell does.
    #[test]
    fn ffi_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        let pdf_path = dir.path().join("doc.pdf");
        std::fs::write(
            &pdf_path,
            syodep_pdf::test_support::pdf_with_pages(&["alpha", "beta"]),
        )
        .unwrap();
        let db_path = CString::new(dir.path().join("db.sqlite3").display().to_string()).unwrap();

        unsafe {
            let app = syo_app_new(std::ptr::null(), db_path.as_ptr());
            assert!(!app.is_null());
            assert!(!syo_app_has_document(app));

            syo_app_set_viewport(app, 595.0, 600.0);
            let c_pdf = CString::new(pdf_path.display().to_string()).unwrap();
            assert!(syo_app_open_document(app, c_pdf.as_ptr()));
            assert!(syo_app_has_document(app));

            // Status text mentions the file and page count.
            let status = syo_app_status_text(app);
            let text = CStr::from_ptr(status).to_str().unwrap().to_owned();
            syo_string_free(status);
            assert!(text.contains("doc.pdf"), "{text}");
            assert!(text.contains("[1/2]"), "{text}");

            // Key events: scroll, then quit.
            let j = CString::new("j").unwrap();
            assert_eq!(syo_app_key_event(app, j.as_ptr()), SYO_EFFECT_REDRAW);
            let q = CString::new("q").unwrap();
            assert_eq!(
                syo_app_key_event(app, q.as_ptr()) & SYO_EFFECT_QUIT,
                SYO_EFFECT_QUIT
            );

            // Visible pages.
            let mut pages = [SyoVisiblePage {
                page: 0,
                x: 0.0,
                y: 0.0,
                width: 0.0,
                height: 0.0,
            }; 8];
            let count = syo_app_visible_pages(app, pages.as_mut_ptr(), pages.len());
            assert!(count >= 1);
            assert_eq!(pages[0].page, 0);

            // Render.
            let bitmap = syo_app_render_page(app, 0);
            assert!(!bitmap.is_null());
            assert_eq!((*bitmap).width, 595);
            assert!(!(*bitmap).data.is_null());
            syo_bitmap_free(bitmap);

            // Caret focus: inactive until entered with `cc`, then valid and movable.
            assert_eq!(syo_app_caret(app).valid, 0);
            let c_key = CString::new("c").unwrap();
            // `cc` is a two-key sequence: one `c` is pending, the second enters.
            syo_app_key_event(app, c_key.as_ptr());
            assert_eq!(syo_app_caret(app).valid, 0);
            syo_app_key_event(app, c_key.as_ptr());
            let caret0 = syo_app_caret(app);
            assert_eq!(caret0.valid, 1);
            let l_key = CString::new("l").unwrap();
            syo_app_key_event(app, l_key.as_ptr());
            let caret1 = syo_app_caret(app);
            assert_eq!(caret1.valid, 1);
            // Moving right does not move the caret left.
            assert!(caret1.x >= caret0.x);
            // Leaving caret focus mode hides the overlay again.
            let esc = CString::new("<Esc>").unwrap();
            syo_app_key_event(app, esc.as_ptr());
            assert_eq!(syo_app_caret(app).valid, 0);

            // Line focus: inactive until entered with `cl`, then valid; `<Esc>`
            // hides it again.
            assert_eq!(syo_app_line(app).valid, 0);
            syo_app_key_event(app, c_key.as_ptr());
            assert_eq!(syo_app_line(app).valid, 0);
            syo_app_key_event(app, l_key.as_ptr());
            assert_eq!(syo_app_line(app).valid, 1);
            syo_app_key_event(app, esc.as_ptr());
            assert_eq!(syo_app_line(app).valid, 0);

            // Out-of-range render fails cleanly.
            let bad = syo_app_render_page(app, 99);
            assert!(bad.is_null());

            syo_app_free(app);
        }
    }

    #[test]
    fn null_arguments_are_tolerated() {
        unsafe {
            assert!(!syo_app_open_document(
                std::ptr::null_mut(),
                std::ptr::null()
            ));
            assert_eq!(syo_app_key_event(std::ptr::null_mut(), std::ptr::null()), 0);
            assert_eq!(
                syo_app_visible_pages(std::ptr::null(), std::ptr::null_mut(), 0),
                0
            );
            syo_bitmap_free(std::ptr::null_mut());
            syo_string_free(std::ptr::null_mut());
            syo_app_free(std::ptr::null_mut());
        }
    }

    #[test]
    fn bad_config_becomes_warning_not_failure() {
        let dir = tempfile::tempdir().unwrap();
        let config_path = dir.path().join("config.toml");
        std::fs::write(&config_path, "this is [[ not toml").unwrap();
        let c_config = CString::new(config_path.display().to_string()).unwrap();
        unsafe {
            let app = syo_app_new(c_config.as_ptr(), std::ptr::null());
            assert!(!app.is_null());
            let status = syo_app_status_text(app);
            let text = CStr::from_ptr(status).to_str().unwrap().to_owned();
            syo_string_free(status);
            assert!(text.contains("default config"), "{text}");
            syo_app_free(app);
        }
    }

    #[test]
    fn resolve_open_dir_defaults_to_cwd() {
        let cwd = std::env::current_dir().unwrap().display().to_string();
        let r = resolve_open_dir(None);
        assert_eq!(r.path, cwd);
        assert_eq!(r.source, "launch directory");
        assert!(r.warning.is_none());

        // An empty / whitespace override is treated as unset.
        let r = resolve_open_dir(Some("   "));
        assert_eq!(r.path, cwd);
        assert!(r.warning.is_none());
    }

    #[test]
    fn resolve_open_dir_uses_existing_configured_dir() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().display().to_string();
        let r = resolve_open_dir(Some(&path));
        assert_eq!(r.path, path);
        assert!(r.source.contains("files.open_dir"));
        assert!(r.warning.is_none());
    }

    #[test]
    fn resolve_open_dir_falls_back_when_configured_dir_missing() {
        let cwd = std::env::current_dir().unwrap().display().to_string();
        let r = resolve_open_dir(Some("/no/such/syodep/dir"));
        assert_eq!(r.path, cwd);
        assert!(r.source.contains("not found"));
        assert!(r.warning.is_some());
    }

    #[test]
    fn open_dir_getters_wire_through_config() {
        let dir = tempfile::tempdir().unwrap();
        let config_path = dir.path().join("config.toml");
        let papers = dir.path().join("papers");
        std::fs::create_dir(&papers).unwrap();
        // TOML literal string (single quotes) so Windows backslash paths are
        // not mangled by basic-string escape processing.
        std::fs::write(
            &config_path,
            format!("[files]\nopen_dir = '{}'\n", papers.display()),
        )
        .unwrap();
        let c_config = CString::new(config_path.display().to_string()).unwrap();
        unsafe {
            let app = syo_app_new(c_config.as_ptr(), std::ptr::null());
            assert!(!app.is_null());
            let open = syo_app_open_dir(app);
            let open_s = CStr::from_ptr(open).to_str().unwrap().to_owned();
            syo_string_free(open);
            assert_eq!(open_s, papers.display().to_string());
            let src = syo_app_open_dir_source(app);
            let src_s = CStr::from_ptr(src).to_str().unwrap().to_owned();
            syo_string_free(src);
            assert!(src_s.contains("files.open_dir"), "{src_s}");
            syo_app_free(app);
        }
    }

    #[test]
    fn missing_open_dir_warns_and_falls_back() {
        let dir = tempfile::tempdir().unwrap();
        let config_path = dir.path().join("config.toml");
        std::fs::write(
            &config_path,
            "[files]\nopen_dir = \"/no/such/syodep/dir\"\n",
        )
        .unwrap();
        let c_config = CString::new(config_path.display().to_string()).unwrap();
        let cwd = std::env::current_dir().unwrap().display().to_string();
        unsafe {
            let app = syo_app_new(c_config.as_ptr(), std::ptr::null());
            assert!(!app.is_null());
            let open = syo_app_open_dir(app);
            let open_s = CStr::from_ptr(open).to_str().unwrap().to_owned();
            syo_string_free(open);
            assert_eq!(open_s, cwd);
            // The fallback surfaces in the status line.
            let status = syo_app_status_text(app);
            let text = CStr::from_ptr(status).to_str().unwrap().to_owned();
            syo_string_free(status);
            assert!(text.contains("open_dir not found"), "{text}");
            syo_app_free(app);
        }
    }

    #[test]
    fn default_paths_are_nonempty() {
        unsafe {
            let config = syo_default_config_path();
            let db = syo_default_db_path();
            assert!(!CStr::from_ptr(config).to_str().unwrap().is_empty());
            assert!(CStr::from_ptr(db).to_str().unwrap().contains("syodep"));
            syo_string_free(config);
            syo_string_free(db);
        }
    }
}
