//! Generates `include/syodep_ffi.h` for the Qt shell via cbindgen.

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").expect("set by cargo");
    let out = std::path::Path::new(&crate_dir)
        .join("include")
        .join("syodep_ffi.h");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("SYODEP_FFI_H".to_owned()),
        cpp_compat: true,
        documentation: true,
        header: Some("/* Generated by cbindgen from crates/syodep-ffi. Do not edit. */".to_owned()),
        ..Default::default()
    };

    match cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file(out);
        }
        Err(e) => {
            // Header generation failures must fail the build loudly: the Qt
            // shell cannot compile against a stale or missing header.
            panic!("cbindgen failed: {e}");
        }
    }
    println!("cargo:rerun-if-changed=src/lib.rs");
}
